### ISSUE TITLE
db.close() issue

### ISSUE THREAD

**Issue by ivanrkv** [mafintosh/mongojs#224]
Hey,
First of, awesome module.
Second of, I'm just starting to use mongodb, I noticed that my app after running for a while, throws a "EMFILE, too many open files", which I figured has something to do with me not closing all the database connections. So I tried doing just that, with db.close() in my functions, but that's throwing a "Object [object Object] has no method 'destroy'". Do you think that's something in mongojs or should I hunt for other problems in my code?

Thank you for your attention.

**Comment by saintedlama** [comment]
Which version of mongojs do you use? I did a test to reproduce this error in version 1.0.x but wasn't able to. My code
```javascript
var mongojs = require('mongojs');
var db = mongojs('mongodb://localhost/test', ['a']);

db.a.find({}, function(err, items) { console.log(err, items); });
// Prints items
[ { _id: 55acfcdacceda9fc09d69d5e, name: '' },
  { _id: 55acfcddcceda9fc09d69d5f, name: '' },
  { _id: 55acfce1cceda9fc09d69d60, name: '' } ]

db.close();

db.a.find({}, function(err, items) { console.log(err, items); });
// Prints MongoError
{ [MongoError: connection to host localhost:27017 was destroyed]
  name: 'MongoError',
  message: 'connection to host localhost:27017 was destroyed' }

```

**Comment by ivanrkv** [comment]
Hey, 
Thanks for your reply!
I am using mongojs@1.0.2

`var getUsers = function(callback) {
var uri = 'mongodb://user:pass@localhost:27017/test,
db = mongojs(uri, ['users']);
db.users.find({status:1}, function(err, users) { console.log(users); } );
db.close()
}`

And the above is what results in Object [object Object] has no method 'destroy'.

**Comment by saintedlama** [comment]
Your code seems a bit odd because you change a db variable that is defined outside of the function scope. May it be that this error arises from this issue? Could you `console.log(db)` before closing db?

**Comment by saintedlama** [comment]
After a second look at your code I guess I found the problem. Your closing a db that is not yet open. Databases in mongojs get opened on the first access to the database that requires an open db. In your case this is `db.users.find`.

So, moving close to the `db.users.find` callback should fix the problem (I made db a `var`):

```javascript
var getUsers = function(callback) {
    var uri = 'mongodb://user:pass@localhost:27017/test',
    var db = mongojs(uri, ['users']);
    db.users.find({status:1}, function(err, users) { 
      console.log(users); 
      db.close();
    });
}
```

**Comment by mafintosh** [comment]
@saintedlama could we fix this somehow so that you can close a db that hasn't been opened?

**Comment by saintedlama** [comment]
@mafintosh this was an educated guess. Implemented test to assure that an unopened db can be closed in bf7473e82acb6ed09bf2f078fdeef7b8fab22a72

So the problem of the issue may be the use of some global/non function scope `db` variable when closing. And closing before or while `db.users.find` is running is an issue as well.

**Comment by colinbes** [comment]
I'm current using master branch and also get error when using as:

```
db.mydoc.find({}, function(err, docs) {
	if (err) {
		console.log(err);
	} else {
		console.log(docs);
	}
	db.close();
})
```

Error thrown:
```
/Users/colinbes/coding/node/mongotests/node_modules/mongojs/node_modules/mongodb-core/lib/cursor.js:247
      throw err;

TypeError: Object [object Object] has no method 'destroy'
    at /Users/colinbes/coding/node/mongotests/node_modules/mongojs/lib/database.js:37:12
    at apply (/Users/colinbes/coding/node/mongotests/node_modules/mongojs/node_modules/thunky/index.js:16:28)
    at null._getServer (/Users/colinbes/coding/node/mongotests/node_modules/mongojs/node_modules/thunky/index.js:27:3)
    at Database.close (/Users/colinbes/coding/node/mongotests/node_modules/mongojs/lib/database.js:35:8)
    at /Users/colinbes/coding/node/mongotests/mongojs.js:13:5
```

**Comment by ivanrkv** [comment]
Hello everyone,
saintedlama, thank you for your reply, I tested but I found that the error still occurs, like colinbes stated. I did console.log(db) and it seems that the db object is fine. 

    { _getServer: [Function],
      _dbname: 'testdb',
      ObjectId:
       { [Function: ObjectID]
         index: 13072488,
         createPk: [Function: createPk],
         createFromTime: [Function: createFromTime],
         createFromHexString: [Function: createFromHexString],
         isValid: [Function: isValid],
         ObjectID: [Circular],
         ObjectId: [Circular] },
      users: { _name: 'users', _dbname: 'testdb', _getServer: [Function] } }

**Comment by ivanrkv** [comment]
Any suggestions guys?

**Comment by saintedlama** [comment]
Currently I've no idea how this error can be reproduced. All code fragments I tried work as expected.

**Comment by ivanrkv** [comment]
Can I ask for your console.log(db) before closing? I feel like the error is on my end, I'd like to compare our outputs.

**Comment by ivanrkv** [comment]
Also, the code you've posted above (https://github.com/mafintosh/mongojs/issues/224#issuecomment-124001669) works on my system. I should've tested that earlier.

**Comment by colinbes** [comment]
I can test my end next week but I am reliably able to reproduce this, actually 100% of the time as per code snippet I submitted.

**Comment by ivanrkv** [comment]
I removed the credentials in the uri string (mongodb://user:pass@localhost:27017/test), changing it to mongodb://localhost:27017/test and now it works

**Comment by colinbes** [comment]
Interesting as it doesn't work on mine. Guess we need to figure out differences in setup differences.

**Comment by colinbes** [comment]
I recall that. I think it only failed when using credentials.

**Comment by ivanrkv** [comment]
Okay, so, as I said I'm pretty new to the whole mongodb thing. This lead me to look into how the db authentication actually happens. Turns out that authentication is disabled by default (wtf..?). Enabling authentication on ubuntu server is done by uncommenting auth=true line in /etc/mongod.conf . Command line db access no longer works without credentials, so that's good. Thanks to you guys for turning me on to that :).
BUT. Testing with mongojs revealed a couple of things. Using the uri string with credentials still causes a object has no method destroy error. Also, if I remove the credentials from the string, it still connects to the db, which I find strange (because authentication seems to be enabled), but I think that could be attributed to node running as a process that belongs to a user that has db access. 
@saintedlama could you test your db with credentials?

**Comment by ChrisShannon** [comment]
I am seeing the same issue. Started happening after upgraded Mongo to 3.0.5 and ScramSHA1.

**Comment by mikaoelitiana** [comment]
Hi everybody, I have just had the same issue and have found no solution yet so I have to remove db.close() from my code. Any new idea about this?

**Comment by kmiyashiro** [comment]
I'm also getting this with a mongo 3.0.5 server and using credentials with latest mongojs with both node 0.10 and 0.12

**Comment by SepiaApps** [comment]
Also seeing this issue.

**Comment by smolyakoff** [comment]
Also started occuring when upgraded to mongo 3 and ScramSHA1

**Comment by smolyakoff** [comment]
This is my current workaround. *_getServer* returns Session instance, not Server instance for my setup with mongodb 3 
```js
db._getServer(function(err, server) {
        server = _.isFunction(server.destroy) ? server : server.topology;
        if (server.destroy) {
                server.destroy(true, true);
         }
});

**Comment by ivanrkv** [comment]
@smolyakoff thanks for your solution. After a quick test, it seems to be working. hopefully we'll see a proper module integration.

**Comment by saintedlama** [comment]
Fixed in version 2.0.0 :tada:

**Comment by ChrisShannon** [comment]
Great, thanks!
